name: dbt_v1.8.6_bigquery_build_full_refresh

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_DEMO_TOKEN }}
  DBT_BIGQUERY_DEMO_PROJECT: ${{ secrets.DBT_BIGQUERY_DEMO_PROJECT }}
  
jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.8.6
        with:
          dbt_command: "dbt deps --profiles-dir ./integration_tests/profiles/bigquery --target dev"

      - name: dbt-debug
        uses: mwhitaker/dbt-action@v1.8.6
        with:
          dbt_command: "dbt debug --profiles-dir ./integration_tests/profiles/bigquery --target dev"

      - name: dbt-build
        uses: mwhitaker/dbt-action@v1.8.6
        with:
          dbt_command: 'dbt build --full-refresh --profiles-dir ./integration_tests/profiles/bigquery --target dev'

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-build.outputs.result }}"
        shell: bash
