name: dbt_v1.8.6_redshift_build_full_refresh

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  DBT_REDSHIFT_HOST: ${{ secrets.DBT_REDSHIFT_HOST }}
  DBT_REDSHIFT_CI_USER: ${{ secrets.DBT_REDSHIFT_CI_USER }}
  DBT_REDSHIFT_CI_PASSWORD: ${{ secrets.DBT_REDSHIFT_CI_PASSWORD }}
  DBT_REDSHIFT_DEMO_DATABASE: ${{ secrets.DBT_REDSHIFT_DEMO_DATABASE }}
  
jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.8.6
        with:
          dbt_command: "dbt deps --profiles-dir ./integration_tests/profiles/redshift --target dev"
          
      - name: dbt-debug
        uses: mwhitaker/dbt-action@v1.8.6
        with:
          dbt_command: "dbt debug --profiles-dir ./integration_tests/profiles/redshift --target dev"

      - name: dbt-build
        uses: mwhitaker/dbt-action@v1.8.6
        with:
          dbt_command: 'dbt build --full-refresh --profiles-dir ./integration_tests/profiles/redshift --target dev'

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-build.outputs.result }}"
        shell: bash
